spring:
  profiles: local
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8082
app:
  config:
    queue:
      name: shipment-local-queue  
    manager:
      host-url: http://localhost:8088/manager/shipment  
    fields:
      ref-number: ":20:"
      execution-date: ":32A:"
      execution-date-format: YYMMDD
      fx-rate: ":36:"
    suspicious:
      condition:
        source-country: AT
        service-code: ATZ
        execution-date-text: Ship dual FERT chem
        names: Mark Imaginary,Govind Real,Shakil Maybe,Chang Imagine 
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8092
app:
  config:
    queue:
      name: shipment-dev-queue
    manager:
      host-url: http://localhost:8088/manager/shipment  
    fields:
      ref-number: ":20:"
      execution-date: ":32A:"
      execution-date-format: YYMMDD
      fx-rate: ":36:"
    suspicious:
      condition:
        source-country: AT
        service-code: ATZ
        execution-date-text: Ship dual FERT chem
        names: Mark Imaginary, Govind Real, Shakil Maybe, Chang Imagine 
