spring:
  profiles: local
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8082
app:
  config:
    queue:
      name: shipment-local-queue  
    manager:
      host-url: http://localhost:8088/manager/shipment  
    fields:
      ref-number: ":20:"
      execution-date: ":32A:"
      fx-rate: ":36:"
    validation:
      fields-pattern: ^(.{1})(.{22})(.{20})(.{1})(.{19})(.{3})(.{3})(.{2}).*
      request-type-value: G 
      format-type-value: U
      amount-pattern: ^([\+\-]{0,1})([0-9]{14,15})(\.)([0-9]{3}) 
      execution-date-format: YYMMDD
    suspicious:
      condition:
        source-country: AT
        service-code: ATZ
        execution-date-text: Ship dual FERT chem
        names: Mark Imaginary,Govind Real,Shakil Maybe,Chang Imagine 
        status:
          invalid: Suspicious shipment DELIM AT DELIM AT ATZ AT DELIM {TRN}
          valid: Nothing found, all okay
        
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8092
app:
  config:
    queue:
      name: shipment-dev-queue
    manager:
      host-url: http://localhost:8088/manager/shipment  
    fields:
      ref-number: ":20:"
      execution-date: ":32A:"
      fx-rate: ":36:"
    validation:
      fields-pattern: ^(.{1})(.{22})(.{20})(.{1})(.{19})(.{3})(.{3})(.{2}).*
      request-type-value: G 
      format-type-value: U
      amount-pattern: ^([\+\-]{0,1})([0-9]{14,15})(\.)([0-9]{3}) 
      execution-date-format: YYMMDD
    suspicious:
      condition:
        source-country: AT
        service-code: ATZ
        execution-date-text: Ship dual FERT chem
        names: Mark Imaginary,Govind Real,Shakil Maybe,Chang Imagine 
        status:
          invalid: Suspicious shipment DELIM AT DELIM AT ATZ AT DELIM {TRN}
          valid: Nothing found, all okay
