spring:
  profiles: local
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8086
app:
  config:
    queue:
      name: shipment-local-queue  
    manager:
      host-url: http://localhost:8087/validation-manager/shipment  
    
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://0.0.0.0:61616
server:
  port: 8092
app:
  config:
    queue:
      name: shipment-dev-queue
    manager:
      host-url: http://localhost:8087/validation-manager/shipment  